config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :posts, only: [:show, :new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  
  mount_uploader :image, ImageUploader
  validates :comment, length: { maximum: 255 }
  validates :image, presence: { message: 'を選択してください。' }
  
  has_many :favorites, dependent: :destroy
  has_many :reverses_of_favorite, class_name: 'Favorite', foreign_key: 'post_id'
  has_many :likers, through: :reverses_of_favorite, source: :user
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  has_many :posts
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites, dependent: :destroy
  has_many :likes, through: :favorites, source: :post
  
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_posts
    Post.where(user_id: self.following_ids + [self.id])
  end
  
  def like(post)
      self.favorites.find_or_create_by(post_id: post.id)
  end
  
  def dislike(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end
  
  def likes?(post)
    self.likes.include?(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  include Pagy::Backend
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_posts = user.posts.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_likes = user.likes.count
  end
  
 
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in

  def create
    post = Post.find(params[:post_id])
    current_user.like(post)
    flash[:success] = 'いいねしました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.dislike(post)
    flash[:success] = 'いいねを取り消しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def show
    @post = Post.find_by(id: params[:id])
  end 
  
  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      flash[:success] = '写真を投稿しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '写真の投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    #byebug
    @post.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to root_url
  end
  
  private
  
  def post_params
    params.require(:post).permit(:comment, :image)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザーをフォローしました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザーのフォローを解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @posts = current_user.feed_posts.order(id: :desc)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :likes]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.where.not(id: current_user.id).order(id: :desc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc)
    counts(@user)
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'アカウントを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'アカウントの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'プロフィールを編集しました。'
      redirect_to @user
    else
    # byebug

      flash.now[:danger] = 'プロフィールの編集に失敗しました。'
      render :edit
    end   
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings
    counts(@user)
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.likes
    counts(@user)
  end  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image )
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.likes?(post) %>
  <%= form_with(model: current_user.favorites.find_by(post_id: post.id), method: :delete) do |f| %>
    <%= hidden_field_tag :post_id, post.id, id: "post_#{post.id}" %>
    <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
      <i class="fas fa-heart unlike-btn"></i>
      <%= Favorite.where(post_id: post.id).length %>
    <% end %>  
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build) do |f| %>
    <%= hidden_field_tag :post_id, post.id, id: "post_#{post.id}" %>
    <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
      <i class="far fa-heart like-btn"></i>
      <%= Favorite.where(post_id: post.id).length %> 
     <% end %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-2" style="z-index: 1;">
  <nav class="navbar navbar-expand-sm">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">みんなのペット紹介</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <div class="btn-group">
            <ul class="navbar-nav">
              <li class="ms-3"><%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %></li>
            </ul>
            <ul class="navbar-nav">
              <li class="mx-3"><%= link_to '投稿する', new_post_path, class: 'nav-link' %></li>
            </ul>
            <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to 'プロフィール', user_path(current_user), class: 'nav-link' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'プロフィールを編集する', edit_user_path(current_user), class: 'nav-link' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'アカウント登録', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>PetShow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>  
  </body>
</html>

app/views/posts/_posts.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <ul class="list-unstyled mt-2">
      <% posts.each do |post| %>
        <li class="mb-4 d-flex card">
          <div>
            <div>
              <%= image_tag post.user.image.url, class: 'user_image', alt: "" %>
              <span class="m-3"><%= link_to post.user.name, user_path(post.user), class: "text-decoration-none" %></span>
            </div>
            <div class="mt-2" style="overflow-wrap: break-word;"><%= simple_format(post.comment) %></div>
            <div class="text-center mb-3">
              <%= link_to(post_path(post)) do %>
                <%= image_tag post.image.url , alt: "", class: "photo"%>
              <% end %>
            </div>
            <div class="text-secondary row">
              <div class="mt-1 col-3">
                投稿日 <%= post.created_at.strftime('%Y/%m/%d') %>
              </div>   
              <div class="col-3">  
                <%= render 'favorites/favorite_button', post: post %>
              </div>   
              <div class="mt-1 col-3">
                <% if current_user == post.user %><%= link_to "投稿を削除する", post, method: :delete, data: { confirm: "本当にこの投稿を削除してよろしいですか？" }, class: 'btn text-secondary btn-sm p-0' %><% end %>
              </div>  
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<div class="py-4 border rounded border-4 border-info">  
  <div class="mb-4 text-center">
    <h3>ペットの写真投稿ページ</h3>
  </div>

  <%= form_for (@post) do |f| %>
    <div class="row">
      <aside class="col-sm-10 offset-sm-1">
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.label :comment, 'コメント' %>
        <div class="mb-3">
          <%= f.text_area :comment, class: 'form-control', rows: 4 %>
        </div>
        
        <div>
          <%= f.label :image, "写真" %>
        </div>
        <div class="mb-3">
          <%= f.file_field :image, class: "image"%>
        </div>  
          
        <div class="post-new-btn">
          <%= f.submit '投稿する！', class: 'btn btn-lg'%>
        </div>  
      </aside>
    </div>  
  <% end %>
</div>  

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <ul class="list-unstyled mt-3">
      <li class="d-flex card">
        <div>
          <div>
            <%= image_tag @post.user.image.url, class: 'user_image',  alt: "" %>
            <span class="m-3"><%= link_to @post.user.name, user_path(@post.user), class: "text-decoration-none" %></span>
          </div>
          <div class="mt-2" style="overflow-wrap: break-word;"><%= simple_format(@post.comment) %></div>
          <div class="text-center mb-3">
              <%= image_tag @post.image.url, alt: "", class: "photo"%>
          </div>  
          <div class="text-secondary row">
            <div class="mt-1 col-3">
              投稿日 <%= @post.created_at.strftime('%Y/%m/%d') %>
            </div>   
            <div class="col-3">  
              <%= render 'favorites/favorite_button', post: @post %>
            </div>
            <div class="mt-1 col-3">
              <% if current_user == @post.user %><%= link_to "投稿を削除する", @post, method: :delete, data: { confirm: "本当にこの投稿を削除してよろしいですか？" }, class: 'btn text-secondary btn-sm p-0' %><% end %>
            </div>  
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id, id: "follow_#{user.id}" %>
      <%= f.submit ' フォロー中 ', data: { confirm: "フォローを解除しますか？" }, class: 'btn btn-primary rounded-pill w-100' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id, id: "follow_#{user.id}" %>
      <%= f.submit 'フォローする', class: 'btn btn-light border-primary border-1 text-primary rounded-pill w-100' %>
    <% end %>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <%= render 'posts/posts', posts: @posts %>
<% else %>
　<div class="pt-5 pb-4 my-4 border rounded">
    <div class="text-center">
      <h1>みんなにペットを紹介しよう！</h1>
      <div class="mt-4 pb-2">
        <%= link_to 'アカウント登録はこちら', signup_path, class: 'btn btn-lg' %>
      </div>
      <h6 class="my-2 text-center">アカウントをお持ちですか？ <%= link_to 'ログインする', login_path %></h6>
    </div>
  </div>
  <div class="img">
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="mb-3 d-flex justify-content-center">
        <div class="rounded-circle">
          <%= image_tag user.image.url, class: 'user_image mt-3', alt: "" %>
        </div>
        <div class="p-4">
          <%= link_to user.name, user_path(user), class: "text-decoration-none" %>
        </div>  
        <div class="m-3">  
          <%= render 'relationships/follow_button', user: user %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class="pt-3 mb-3 border rounded border-4 border-info">
  <%= form_for(@user) do |f| %>
  
    <div class="mt-1 text-center">
      <%= image_tag @user.image.url, class: 'user_img mt-3', alt: "" %>
      <%= f.label :image, "変更", class: "image_input_btn" %>
      <%= f.file_field :image, class: "image_form" %>  
    </div>  
    
     
    
    <div class="row"> 
      <div class="col-sm-6 offset-sm-3">
        <div class="mt-5 mb-3">
        <%= render 'layouts/error_messages', model: f.object %>  
          <%= f.label :name, 'ユーザー名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="mb-3">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
      
        <div class="mb-3">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
      
        <div class="mb-5">
          <%= f.label :password_confirmation, 'パスワード（確認）' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      </div>   
      <div class="d-flex justify-content-center">
  　     <%= f.submit '保存する', class: 'btn btn-lg' %>
  　   </div>
  　</div>   
  <% end %>
</div>

app/views/users/followers.html.erb
<ul class="list-unstyled">
  <li class="mb-4 d-flex justify-content-center">
    <div class="mr-3">
      <%= image_tag @user.image.url, class: 'user_img mt-3', alt: "" %>
    </div>  
    <h1 class="m-4 pt-2"><%= @user.name %></h1>
    <div class="m-4 pt-3">
      <%= render 'relationships/follow_button', user: @user %>
    </div>  
  </li>
</ul>
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge bg-light text-primary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">いいね  <span class="badge bg-light text-primary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中 <span class="badge bg-light text-primary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge bg-light text-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<ul class="list-unstyled">
  <li class="mb-4 d-flex justify-content-center">
    <div class="mr-3">
      <%= image_tag @user.image.url, class: 'user_img mt-3', alt: "" %>
    </div>  
    <h1 class="m-4 pt-2"><%= @user.name %></h1>
    <div class="m-4 pt-3">
      <%= render 'relationships/follow_button', user: @user %>
    </div>  
  </li>
</ul>
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge bg-light text-primary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">いいね  <span class="badge bg-light text-primary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中  <span class="badge bg-light text-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge bg-light text-primary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<ul class="list-unstyled">
  <li class="mb-4 d-flex justify-content-center">
    <div class="mr-3">
      <%= image_tag @user.image.url, class: 'user_img mt-3', alt: "" %>
    </div>  
    <h1 class="m-4 pt-2"><%= @user.name %></h1>
    <div class="m-4 pt-3">
      <%= render 'relationships/follow_button', user: @user %>
    </div>  
  </li>
</ul>
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge bg-light text-primary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">いいね  <span class="badge bg-light text-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中  <span class="badge bg-light text-primary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge bg-light text-primary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'posts/posts', posts: @likes %>
  </div>
</div>

app/views/users/new.html.erb
<div class="py-4 border rounded border-4 border-info">
    <div class="mb-4 text-center">
      <h1>アカウント登録</h1>
    </div>
    
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div class="mb-3">
            <%= f.label :name, 'ユーザー名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
  
          <div class="mb-3">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
    
          <div class="mb-3">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
    
          <div class="mb-3">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit 'アカウント登録', class: 'btn btn-lg w-100' %>
        <% end %>
      </div>
    </div>
    <p class="my-2 pt-2 text-center">アカウントをお持ちですか？ <%= link_to 'ログインする', login_path %></p>
</div>    

app/views/users/show.html.erb
<ul class="list-unstyled">
  <li class="mb-4 d-flex justify-content-center">
    <div class="mr-3">
      <%= image_tag @user.image.url, class: 'user_img mt-3', alt: "" %>
    </div>  
    <h1 class="m-4 pt-2"><%= @user.name %></h1>
    <div class="m-4 pt-3">
      <%= render 'relationships/follow_button', user: @user %>
    </div>  
  </li>
</ul>
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge bg-light text-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">いいね  <span class="badge bg-light text-primary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー中  <span class="badge bg-light text-primary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge bg-light text-primary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>